### ISSUE TITLE
Add an overview of changes in v4

### ISSUE THREAD

**Issue by SadieCat** [inspircd/docs#187]
The current v4 changelog isn't very useful for people who are upgrading as it doesn't give people a summary of all of the changes in the release. We should add a new docs page with a more higher level overview of the changes.

I've started work on this [over here](https://github.com/inspircd/inspircd-docs/compare/master...SadieCat:inspircd-docs:overview) but it would be good to have some help with suggestions for what should be in it as its a big task.

**Comment by clinew** [comment]
When following the link I get:

> There isn’t anything to compare.
> We couldn’t figure out how to compare these references, do they point to valid commits?

Anyways, the removal of the `ssl_mbedtls` extra module should be added.

**Comment by SadieCat** [comment]
That branch was removed because it was merged already.

https://docs.inspircd.org/4/overview/
