### ISSUE TITLE
MariaDB support?

### ISSUE THREAD

**Issue by robertsilen** [inspircd/docs#239]
Hello, is there any particular reason MariaDB is not mentioned as supported, or could it be added to the documentation?  https://docs.inspircd.org/3/modules/mysql/

**Comment by SadieCat** [comment]
There's no particular reason why its not listed. The module should build against any MySQL variant.

That said, whilst MariaDB is a fork of MySQL its not fully compatible with MySQL on all systems. e.g. on Debian systems you need a compatibility layer (`libmariadb-dev-compat`) to build against the MariaDB client libraries and there have been some additions to MySQL that have not been replicated in MariaDB. I'm unsure as to whether they plan to make future changes which will make it even more incompatible and I'd like to avoid the situation we ended up in with LibreSSL where we documented support and they ended up breaking so much compatibility that we ended up with a mess of fragile compatibility code in v3 and had to drop support in v4.

**Comment by cvicentiu** [comment]
@SadieCat in general MariaDB seldomly breaks backwards compatibility. We are also willing to work with you and ensure things upgrade smoothly.


What would be a good direction towards making sure we do not break compatibility in your mind?

We can set up a CI system on buildbot.mariadb.org that runs for every push and runs your projects test cases, but I am not familiar enough to be able to quantify the exact requirements. We have done this for WordPress for instance.

Of course we do not have infinite resources, but we want to be good open source players and we care about compatibility. A little collaboration can go a long way. :)

Vicențiu - Chief Development Officer MariaDB Foundation

**Comment by SadieCat** [comment]
So far we have encountered the following incompatibilities between MySQL and MariaDB:

- MariaDB uses `MYSQL_VERSION_ID` for its own version which breaks checking for features based on MySQL version. We currently get around this by using `LIBMYSQL_VERSION_ID` for checking for recent features instead which doesn't work on MariaDB as it was forked before that was added. We could get around this by adding specific code for checking for MariaDB but also there's several other MySQL forks which we would need to do the same for and that can end up being really messy. Ideally MySQL forks should be using that version for the version of MySQL they are compatible with and adding their own macro for their version.

- MySQL has removed `MYSQL_OPT_SSL_ENFORCE` in favour of `MYSQL_OPT_SSL_MODE` which isn't supported on MariaDB. This means that [`<database:tls>`](https://docs.inspircd.org/4/modules/mysql/#database) doesn't work on MariaDB. We could add version checking for this but as previously mentioned this is broken.

- MariaDB does not have `mysql_real_connect_dns_srv()` which means [`<database:srv>`](https://docs.inspircd.org/4/modules/mysql/#database) does nothing when built against MariaDB. This is fairly minor but it is a place that the APIs have diverged.

---

I'm happy to document that the MySQL module will probably work against MariaDB (and other MySQL forks) as the differences currently are pretty minor. I'm hesitant to promise future support though on account of how MariaDB's API has diverged slightly and will probably diverge more in the future. This is a general problem with forks imo, you end up with a weird middle space where stuff is nominally a drop-in replacement until you try to deal with any API changes that appeared after the fork happened.

**Comment by robertsilen** [comment]
Hello, thanks for your comments. I added MariaDB to the MySQL documentation for version 3 and 4 of inspircd with PR https://github.com/inspircd/inspircd-docs/pull/241 - I didn't touch the row mentioning tls and srv as per discussion here.

**Comment by robertsilen** [comment]
The MariaDB jira ticket https://jira.mariadb.org/browse/CONC-727 is waiting for feedback - could somebody comment please?
